spring:
  profiles:
    active: dev
---
spring:
  profiles: dev
server:
  port: 8080
logging:
  level:
    org.springframework.web: trace
---
spring:
  profiles: test
server:
  port: 8081
---
spring:
  profiles: pro
server:
  port: 8082